name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Install Ruff
      uses: astral-sh/ruff-action@v3
      with:
        version: "latest"
        
    - run: |
        ruff check dexmcp_dspy_client.py
        ruff check dexmcp/dexmcp_server.py
